name: Test

on: push

jobs:
  test:
    name: Test on Xcode ${{ matrix.xcode }} - ${{ matrix.platform }}
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [11.5, 11.6]
        platform: [iOS]

    steps:
      - uses: actions/checkout@v2

      - run: sudo xcode-select -s '/Applications/Xcode_${{ matrix.xcode }}.app'

      - run: brew unlink node@12

      - name: bootstrap
        run: make install bootstrap

      - run: ls /Applications | grep Xcode
      - run: xcodebuild -showsdks
      - run: xcrun simctl list

      - name: test ${{ matrix.platform }}
        run: make test_${{ matrix.platform }}
